### ISSUE TITLE
Demo 与 Theme 不一致

### ISSUE THREAD

**Issue by magict4** [willerce/hexo-theme-noderce#4]
看了 Demo，觉得blog页面以及文章的排版都非常赞！

但貌似这个主题跟Demo 里面的不是一个主题吧？是我使用上出了什么问题吗？

楼主介意把博客的主题分享一下吗？

谢谢！

**Comment by willerce** [comment]
对的，不是同一个主题。

个人网站的主题还在完善，目前还不确认是否会开源。
